import Head from "next/head";
import { GraphQLClient, gql } from "graphql-request";
import styles from "../styles/Home.module.css";
import BlogCard from "../components/BlogCard";

const graphcms = new GraphQLClient(
  "https://api-ap-northeast-1.hygraph.com/v2/cl9axkls73gcz01um3sccc1v3/master"
);

const QUERY = gql`
  {
    posts {
      id
      title
      datePublished
      slug
      content {
        html
      }
      author {
        name
        avatar {
          url
        }
      }
      coverPhoto {
        createdAt
        publishedAt
        url
      }
    }
  }
`;

export async function getStaticProps() {
  const { posts } = await graphcms.request(QUERY);
  return {
    props: {
      posts,
    },
  };
}

export default function Home({ posts }) {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        {posts.map(({ id, title, author, coverPhoto, datePublished, slug }) => (
          <BlogCard
            key={id}
            title={title}
            author={author}
            coverPhoto={coverPhoto}
            datePublished={datePublished}
            slug={slug}
          ></BlogCard>
        ))}
      </main>
    </div>
  );
}
